import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/trip_model.dart';

// STUB — replace on merge with Member 4/1's implementation
class FirestoreService {
  final FirebaseFirestore _db = FirebaseFirestore.instance;

  Stream<TripModel> streamTrip(String tripId) {
    return _db
        .collection('trips')
        .doc(tripId)
        .snapshots()
        .map((doc) => TripModel.fromFirestore(doc));
  }

  Future<String> createTrip(TripModel trip) async {
    // ASSUMPTION: The document ID will be generated by Firestore if not provided,
    // but the model has a tripId field. I'll use add() and then update it if needed,
    // or just use the generated ID as the tripId.
    DocumentReference ref = await _db.collection('trips').add(trip.toFirestore());
    return ref.id;
  }

  Future<void> updateTripLocation(String tripId, GeoPoint currentLocation) async {
    await _db.collection('trips').doc(tripId).update({
      'currentLocation': {
        'lat': currentLocation.latitude,
        'lng': currentLocation.longitude,
      },
    });
  }

  Future<void> endTrip(String tripId, {required bool arrivedSafely}) async {
    await _db.collection('trips').doc(tripId).update({
      'status': arrivedSafely ? 'completed' : 'alerted',
      'endedAt': FieldValue.serverTimestamp(),
    });
  }
}
